var customNavTree35 = WpNavBar.readTree({
"childArray" : [{   sTitle:'Home',
    bIsWebPath:true,
    sUrl:'index.html',
    sTarget:'_self'},{   sTitle:'scaleartmodels.com',
    sUrl:'http://www.scaleartmodels.com',
    sTarget:'_blank'},{   sTitle:'Scale Art Parts F scale',
    bIsWebPath:true,
    sUrl:'page6.html',
    sTarget:'_self'},{   sTitle:'Scale Art Parts O scale',
    bIsWebPath:true,
    sUrl:'page24.html',
    sTarget:'_self'},{   sTitle:'Gallery',
    bIsWebPath:true,
    sUrl:'page30.html',
    sTarget:'_blank'},{   sTitle:'Contact',
    bIsWebPath:true,
    sUrl:'page7.html'},{   sTitle:'Odering info',
    bIsWebPath:true,
    sUrl:'ordering.html',
    sTarget:'_self'},{   sTitle:'Hints & Tips',
    bIsWebPath:true,
    sUrl:'page9a.html',
    sTarget:'_blank'},{   sTitle:'Links',
    bIsWebPath:true,
    sUrl:'page9.html'}]
});