var customNavTree18 = WpNavBar.readTree({
"childArray" : [{   sTitle:'Home',
    bIsWebPath:true,
    sUrl:'index.html'},{   sTitle:'Scale Art Parts F Scale',
    bIsWebPath:true,
    sUrl:'page6.html',"childArray" : [{   sTitle:'Detail Parts',
        bIsWebPath:true,
        sUrl:'page7a.html',"childArray" : [{   sTitle:'hats',
            sUrl:''}]},{   sTitle:'Sets and Kits',
        bIsWebPath:true,
        sUrl:'page20.html',"childArray" : [{   sTitle:'Fencing',
            bIsWebPath:true,
            sUrl:'page19.html'}]},{   sTitle:'Doors',
        bIsWebPath:true,
        sUrl:'page11.html'},{   sTitle:'Windows',
        bIsWebPath:true,
        sUrl:'page11a.html'}]},{   sTitle:'Scale Art Parts O scale',
    bIsWebPath:true,
    sUrl:'page24.html',"childArray" : [{   sTitle:'REA trucks',
        bIsWebPath:true,
        sUrl:'reatrucks.html'},{   sTitle:'Accessories',
        bIsWebPath:true,
        sUrl:'oaccessories.html'},{   sTitle:'Doors',
        bIsWebPath:true,
        sUrl:'page26.html'},{   sTitle:'Windows',
        bIsWebPath:true,
        sUrl:'page27.html'},{   sTitle:'Walls & Abutments',
        bIsWebPath:true,
        sUrl:'oscalewalls.html'}]},{   sTitle:'scaleartmodels.com',
    sUrl:'http://www.scaleartmodels.com',
    sTarget:'_blank'},{   sTitle:'Gallery',
    bIsWebPath:true,
    sUrl:'page30.html',
    sTarget:'_blank'},{   sTitle:'Contact',
    bIsWebPath:true,
    sUrl:'page7.html'},{   sTitle:'Links',
    bIsWebPath:true,
    sUrl:'page9.html'}]
});