var global_navtree = WpNavBar.readTree({
"childArray" : [{   sTitle:'Home',
    bIsWebPath:true,
    sUrl:'index.html'},{   sTitle:'jonstown',
    bIsWebPath:true,
    sUrl:'page14.html'},{   sTitle:'New Products',
    bIsWebPath:true,
    sUrl:'page12.html'},{   sTitle:'Shop Layout',
    bIsWebPath:true,
    sUrl:'page13.html'},{   sTitle:'Scale Art Parts F Scale',
    bIsWebPath:true,
    sUrl:'page6.html',"childArray" : [{   sTitle:'Detail Parts',
        bIsWebPath:true,
        sUrl:'page7a.html'},{   sTitle:'Sets and Kits',
        bIsWebPath:true,
        sUrl:'page20.html',"childArray" : [{   sTitle:'Fencing',
            bIsWebPath:true,
            sUrl:'page19.html'}]},{   sTitle:'Doors',
        bIsWebPath:true,
        sUrl:'page11.html'},{   sTitle:'Windows',
        bIsWebPath:true,
        sUrl:'page11a.html'}]},{   sTitle:'REA trucks',
    bIsWebPath:true,
    sUrl:'reatrucks.html'},{   sTitle:'Customer Gallery',
    bIsWebPath:true,
    sUrl:'page30.html'},{   sTitle:'Links',
    bIsWebPath:true,
    sUrl:'page9.html'}]
});